In [1]:
import numpy as np

In [17]:
# 3x + 5y = 6 
# 7x - 5y = 9

# Ak = b

A = np.array([[3 , 5] , [7 , -5]])

B = np.array([6 , 9])

In [28]:
print("A =",A)
print("")
print("And")
print("")
print("B =" , B)

A = [[ 3  5]
 [ 7 -5]]

And

B = [6 9]


In [30]:
# We can solve it with linalg.inv() linalg.dot() and also linalg.solve() method for this one we will use linalg.inv() linalg.dot()
X = np.linalg.inv(A).dot(B)

print(X)

[1.5 0.3]


In [40]:
print("x = " , X[0])
print("y = " , X[1])

x =  1.5
y =  0.30000000000000004


In [41]:
#   x + y + z = 6
#       y + z = -4
# 2x + 5y - z = 27

C = np.array([[1 , 1 , 1] , [0 , 1 , 1] , [2 , 5 , -1]])

D = np.array([6 , -4 , 27])

In [42]:
print("C =",C)
print("")
print("And")
print("")
print("D =" , D)

C = [[ 1  1  1]
 [ 0  1  1]
 [ 2  5 -1]]

And

D = [ 6 -4 27]


In [48]:
# For this one linalg.solve() method
Y = np.linalg.solve(C , D)

print(Y)

[10.   0.5 -4.5]


In [44]:
print("x = " , Y[0])
print("y = " , Y[1])
print("z = " , Y[2])

x =  10.000000000000002
y =  0.5
z =  -4.5


In [45]:
# x + y = 4
# 2x + 2y = 8

E = np.array([[1 , 1] , [2 , 2]])

F = np.array([4 , 8])

In [46]:
print("E =",E)
print("")
print("And")
print("")
print("F =" , F)

E = [[1 1]
 [2 2]]

And

F = [4 8]


In [56]:
# Error
Z = np.linalg.solve(E , F)

In [60]:
# The Error because "singular matrix" 
# singular matrix : matrix is one that is not invertible 
# In the above cell Matrix E is singular matrix